apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: zero-app
        metrics_path: /api/metrics
        scheme: http
        static_configs:
          - targets:
              - zero-active.zero-downtime.svc.cluster.local:80
